#!/usr/local/bin/node

var Story = require('inkjs').Story;
var fs = require('fs');
var bytecodePath = process.argv[2];
var bytecode = fs.readFileSync(bytecodePath, 'UTF-8').replace(/^\uFEFF/, '');
var story = new Story(bytecode)
process.stdout.write(story.ContinueMaximally());

