#!/usr/bin/env python3

import os
import sys
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, 'inkjs_system.js')
NODE_PATH = shutil.which("node")
ARGS = [NODE_PATH, SRC] + sys.argv[1:]
os.execv(NODE_PATH, ARGS)
