#!/usr/bin/env python3

import sys
import os

SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'pink-runner.lua')
ROOTDIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PINKDIR = os.path.join(ROOTDIR, 'deps', 'pink')
os.execlpe(SRC, 'pink-runner.lua', "run", sys.argv[1], {"LUA_PATH": PINKDIR+'/?.lua;'+ROOTDIR+'/?.lua'})
